apiVersion: v1
kind: ConfigMap
metadata:
  name: person-service-config
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: persondb
  JWT_ISSUER_URI: http://keycloak:8080/realms/myrealm
  JWK_SET_URI: http://keycloak:8080/realms/myrealm/protocol/openid-connect/certs
